<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Western Blot analysis using Rstudio | Welcome to my portfolio</title>
  <meta name="description" content="5 Western Blot analysis using Rstudio | Welcome to my portfolio" />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Western Blot analysis using Rstudio | Welcome to my portfolio" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Western Blot analysis using Rstudio | Welcome to my portfolio" />
  
  
  

<meta name="author" content="Lamyae el Mahboud" />


<meta name="date" content="2023-06-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="the-guerrila-structure.html"/>
<link rel="next" href="relational-databases.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> My portfolio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#introduction"><i class="fa fa-check"></i><b>1.1</b> introduction</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#my-curriculum-vitae"><i class="fa fa-check"></i><b>1.2</b> My curriculum vitae</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="c.-elegans-plate-experiment-analysis.html"><a href="c.-elegans-plate-experiment-analysis.html"><i class="fa fa-check"></i><b>2</b> C. elegans plate experiment analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="c.-elegans-plate-experiment-analysis.html"><a href="c.-elegans-plate-experiment-analysis.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="c.-elegans-plate-experiment-analysis.html"><a href="c.-elegans-plate-experiment-analysis.html#analyzing-plan"><i class="fa fa-check"></i><b>2.2</b> analyzing plan</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="open-peer-review.html"><a href="open-peer-review.html"><i class="fa fa-check"></i><b>3</b> Open Peer Review</a>
<ul>
<li class="chapter" data-level="3.1" data-path="open-peer-review.html"><a href="open-peer-review.html#introduction-2"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="open-peer-review.html"><a href="open-peer-review.html#clarification"><i class="fa fa-check"></i><b>3.2</b> Clarification</a></li>
<li class="chapter" data-level="3.3" data-path="open-peer-review.html"><a href="open-peer-review.html#the-second-peer-review"><i class="fa fa-check"></i><b>3.3</b> the second peer review</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="the-guerrila-structure.html"><a href="the-guerrila-structure.html"><i class="fa fa-check"></i><b>4</b> The Guerrila structure</a>
<ul>
<li class="chapter" data-level="4.1" data-path="the-guerrila-structure.html"><a href="the-guerrila-structure.html#why-organizing-data"><i class="fa fa-check"></i><b>4.1</b> Why organizing data?</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="western-blot-analysis-using-rstudio.html"><a href="western-blot-analysis-using-rstudio.html"><i class="fa fa-check"></i><b>5</b> Western Blot analysis using Rstudio</a>
<ul>
<li class="chapter" data-level="5.1" data-path="western-blot-analysis-using-rstudio.html"><a href="western-blot-analysis-using-rstudio.html#introduction-3"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="western-blot-analysis-using-rstudio.html"><a href="western-blot-analysis-using-rstudio.html#planning"><i class="fa fa-check"></i><b>5.2</b> planning</a></li>
<li class="chapter" data-level="5.3" data-path="western-blot-analysis-using-rstudio.html"><a href="western-blot-analysis-using-rstudio.html#gel-analysis-and-r"><i class="fa fa-check"></i><b>5.3</b> Gel analysis and R</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="western-blot-analysis-using-rstudio.html"><a href="western-blot-analysis-using-rstudio.html#installation"><i class="fa fa-check"></i><b>5.3.1</b> Installation</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="western-blot-analysis-using-rstudio.html"><a href="western-blot-analysis-using-rstudio.html#getting-started"><i class="fa fa-check"></i><b>5.4</b> Getting started</a></li>
<li class="chapter" data-level="5.5" data-path="western-blot-analysis-using-rstudio.html"><a href="western-blot-analysis-using-rstudio.html#obtaining-data"><i class="fa fa-check"></i><b>5.5</b> Obtaining data</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="western-blot-analysis-using-rstudio.html"><a href="western-blot-analysis-using-rstudio.html#plotting-the-image-and-learning-more-about-imager"><i class="fa fa-check"></i><b>5.5.1</b> plotting the image and learning more about imager</a></li>
<li class="chapter" data-level="5.5.2" data-path="western-blot-analysis-using-rstudio.html"><a href="western-blot-analysis-using-rstudio.html#images-and-data-frames"><i class="fa fa-check"></i><b>5.5.2</b> Images and data frames</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="western-blot-analysis-using-rstudio.html"><a href="western-blot-analysis-using-rstudio.html#working-with-the-created-dataframe"><i class="fa fa-check"></i><b>5.6</b> Working with the created dataframe</a></li>
<li class="chapter" data-level="5.7" data-path="western-blot-analysis-using-rstudio.html"><a href="western-blot-analysis-using-rstudio.html#the-final-product"><i class="fa fa-check"></i><b>5.7</b> The final product</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="relational-databases.html"><a href="relational-databases.html"><i class="fa fa-check"></i><b>6</b> Relational databases</a>
<ul>
<li class="chapter" data-level="6.1" data-path="relational-databases.html"><a href="relational-databases.html#why-using-relational-databases"><i class="fa fa-check"></i><b>6.1</b> Why using relational databases?</a></li>
<li class="chapter" data-level="6.2" data-path="relational-databases.html"><a href="relational-databases.html#the-database"><i class="fa fa-check"></i><b>6.2</b> The database</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="parameters-and-presentations.html"><a href="parameters-and-presentations.html"><i class="fa fa-check"></i><b>7</b> Parameters and Presentations</a>
<ul>
<li class="chapter" data-level="7.1" data-path="parameters-and-presentations.html"><a href="parameters-and-presentations.html#why-using-parameters"><i class="fa fa-check"></i><b>7.1</b> Why using parameters?</a></li>
<li class="chapter" data-level="7.2" data-path="parameters-and-presentations.html"><a href="parameters-and-presentations.html#the-report"><i class="fa fa-check"></i><b>7.2</b> The report</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="rpackage-lamyflow.html"><a href="rpackage-lamyflow.html"><i class="fa fa-check"></i><b>8</b> Rpackage: lamyflow</a>
<ul>
<li class="chapter" data-level="8.1" data-path="rpackage-lamyflow.html"><a href="rpackage-lamyflow.html#why-building-this-rpackage"><i class="fa fa-check"></i><b>8.1</b> Why building this Rpackage?</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="antimicrobial-resistance-amr.html"><a href="antimicrobial-resistance-amr.html"><i class="fa fa-check"></i><b>9</b> Antimicrobial resistance (AMR)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="antimicrobial-resistance-amr.html"><a href="antimicrobial-resistance-amr.html#introduction-4"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i><b>10</b> Resources</a>
<ul>
<li class="chapter" data-level="10.1" data-path="resources.html"><a href="resources.html#youtube-resources"><i class="fa fa-check"></i><b>10.1</b> Youtube resources</a></li>
<li class="chapter" data-level="10.2" data-path="resources.html"><a href="resources.html#references"><i class="fa fa-check"></i><b>10.2</b> References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Welcome to my portfolio</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="western-blot-analysis-using-rstudio" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> Western Blot analysis using Rstudio<a href="western-blot-analysis-using-rstudio.html#western-blot-analysis-using-rstudio" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-3" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Introduction<a href="western-blot-analysis-using-rstudio.html#introduction-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Western Blotting (WB) is a commonly used method in the biological scienes. This technique is used to investigate many features of the protein, ranging from basic protein analysis to disease detection such as cancer and HIV<span class="citation">(<a href="#ref-begumWesternBlottingPowerful2022" role="doc-biblioref">Begum, Murugesan, and Tangutur 2022</a>)</span>. Western Blotting involves three components to achieve this goal: (1) separating based on size, (2) transferring onto a solid surface, and (3) labeling the protein of interest with specific primary and secondary antibodies for visualization<span class="citation">(<a href="#ref-mahmoodWesternBlotTechnique2012" role="doc-biblioref">Mahmood and Yang 2012</a>)</span>. This results in a gel full of different proteins separated by size. Image J is often used to analyze the Western Blot results.
The technique is highly sensitive and can be used to detect even small amounts of protein. It is often used in research into diseases such as cancer and HIV, where specific proteins can be used as markers for diagnosis and treatment.
The next skill im gonna learn is to analyse Western Blots using Rstudio.</p>
</div>
<div id="planning" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> planning<a href="western-blot-analysis-using-rstudio.html#planning" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The first thing I need to do is to read about Western blot analysis in Rstudio. We need to look if people made packages that will help us analyzing the gels and if they succeed. Most of the Western Blot analysis is done with Image J, which makes my search for R codes a bit more difficult.</p>
<ul>
<li>Find articles about photo analysis and Western blot analysis in Rstudio.</li>
<li>Look for a way to obtain data about the pixels of photos .</li>
<li>Try to run the code in the previous step on western blot gels.</li>
<li>Visualize the data in a way the lanes are can be distinguished</li>
</ul>
</div>
<div id="gel-analysis-and-r" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Gel analysis and R<a href="western-blot-analysis-using-rstudio.html#gel-analysis-and-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Not many people have used R to analysis their Western Blot gels. Most of the gel analysis are done with Image J or Python. The reason for that is because R is mostly used for statistical analytics, while Python has multiple purposes. For example data analysis or machine learning.</p>
<p>Even though it was (very) hard to find articles that contain both subjects, I found some packages and that might help me reach my goal. Note that these packages are not related to Western Blot analysis, but are made to analyse photo’s.</p>
<p>The packages that I found that could help me are “<a href="https://www.r-bloggers.com/2014/09/r-image-analysis-using-ebimage/">EBImage</a>” and “<a href="https://dahtah.github.io/imager/imager.html">imager</a>”</p>
<div id="installation" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Installation<a href="western-blot-analysis-using-rstudio.html#installation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To install the “EBImage” package we did the following:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="western-blot-analysis-using-rstudio.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># installation &quot;EBImage&quot;</span></span>
<span id="cb2-2"><a href="western-blot-analysis-using-rstudio.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">&quot;BiocManager&quot;</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>))</span>
<span id="cb2-3"><a href="western-blot-analysis-using-rstudio.html#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;BiocManager&quot;</span>)</span>
<span id="cb2-4"><a href="western-blot-analysis-using-rstudio.html#cb2-4" aria-hidden="true" tabindex="-1"></a>BiocManager<span class="sc">::</span><span class="fu">install</span>(<span class="st">&quot;EBImage&quot;</span>)</span></code></pre></div>
<p>To install the “imager” package, we did the following:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="western-blot-analysis-using-rstudio.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># installation &quot;imager&quot;</span></span>
<span id="cb3-2"><a href="western-blot-analysis-using-rstudio.html#cb3-2" aria-hidden="true" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;asgr/imager&quot;</span>)</span></code></pre></div>
</div>
</div>
<div id="getting-started" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Getting started<a href="western-blot-analysis-using-rstudio.html#getting-started" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To analize a Western Blot gel, we first need a photo. Because we’re testing if we can analize Western Blot gels with R, we’re using a photo with a high contrast and without any smear(s).</p>
<p>The photo we’re using is from an article “<a href="https://www.cell.com/fulltext/S0092-8674%2800%2980416-X">DNA Damage-Induced Phosphorylation of p53 ALleviates Inhibition by MDM2</a>”</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="western-blot-analysis-using-rstudio.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EBImage) <span class="co"># load in &quot;EBImage&quot; package</span></span>
<span id="cb4-2"><a href="western-blot-analysis-using-rstudio.html#cb4-2" aria-hidden="true" tabindex="-1"></a>Image <span class="ot">&lt;-</span> <span class="fu">readImage</span>(<span class="st">&#39;data/Westernblot_photo.png&#39;</span>) <span class="co">#read in westernblot phot</span></span>
<span id="cb4-3"><a href="western-blot-analysis-using-rstudio.html#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(Image) <span class="co">#display image</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>We could manipulated the contrast to our liking. The contrast can be changed using the multiplication operator(<code>*</code>).
if the number after the multiplication operator is <code>1 &gt; X</code>, you’ll get a photo with a lower contrast. If the number after the multiplaction operator is <code>1 &lt; X</code>, you’ll get a phtot with a higher contrast. Note that if you’re using multiple photo’s for an analyse, you’ll need the set the same setting for every photo.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="western-blot-analysis-using-rstudio.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EBImage) <span class="co">#load in &quot;EBImage&quot; package</span></span>
<span id="cb5-2"><a href="western-blot-analysis-using-rstudio.html#cb5-2" aria-hidden="true" tabindex="-1"></a>Image3 <span class="ot">&lt;-</span> Image <span class="sc">*</span> <span class="fl">0.5</span> <span class="co">#set contrast to 0.5</span></span>
<span id="cb5-3"><a href="western-blot-analysis-using-rstudio.html#cb5-3" aria-hidden="true" tabindex="-1"></a>Image4 <span class="ot">&lt;-</span> Image <span class="sc">*</span> <span class="fl">1.1</span> <span class="co">#set contrast to 1.1</span></span>
<span id="cb5-4"><a href="western-blot-analysis-using-rstudio.html#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(Image3); <span class="fu">display</span>(Image4) <span class="co">#display both images next to each other. </span></span></code></pre></div>
<p><img src="_main_files/figure-html/contrast-1.png" width="672" /><img src="_main_files/figure-html/contrast-2.png" width="672" /></p>
<p>The EBImage package has more functions we could use, like cropping, Gamma Correction and Color Management. Ebimage is a good and easy to use package to give your Western Blot the right colours and contrast.</p>
</div>
<div id="obtaining-data" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Obtaining data<a href="western-blot-analysis-using-rstudio.html#obtaining-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>From now on, it gets a bit harder. A big difference between R and Image J when it comes to Western Blot photo’s, is that with Image J you could <em>see</em> which lane you’re working with and manually select the lane you wanted to analize. If a lane wasn’t imported for the analize, you could easly skip that lane. With R, we need to use the x-axis and y-axis of a photo while analyzing.</p>
<div id="plotting-the-image-and-learning-more-about-imager" class="section level3 hasAnchor" number="5.5.1">
<h3><span class="header-section-number">5.5.1</span> plotting the image and learning more about imager<a href="western-blot-analysis-using-rstudio.html#plotting-the-image-and-learning-more-about-imager" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To plot the image, we’re using the <code>plot</code> function of the <code>imager</code> package.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="western-blot-analysis-using-rstudio.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(imager)</span>
<span id="cb6-2"><a href="western-blot-analysis-using-rstudio.html#cb6-2" aria-hidden="true" tabindex="-1"></a>im <span class="ot">&lt;-</span> <span class="fu">load.image</span>(<span class="st">&#39;data/Westernblot_photo.png&#39;</span>)</span>
<span id="cb6-3"><a href="western-blot-analysis-using-rstudio.html#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(im)</span></code></pre></div>
<p><img src="_main_files/figure-html/plot%20image-1.png" width="672" /></p>
<p>The y-axis runs downwards, and the origin is located at the top-left corner, which is the conventional coordinate system for images. Imager consistently employs this coordinate system. the image data is classified as ‘cimg’.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="western-blot-analysis-using-rstudio.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(im) <span class="co">#shows class of the photo</span></span></code></pre></div>
<pre><code>## [1] &quot;cimg&quot;         &quot;imager_array&quot; &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="western-blot-analysis-using-rstudio.html#cb9-1" aria-hidden="true" tabindex="-1"></a>im <span class="co">#will give information about the photo</span></span></code></pre></div>
<pre><code>## Image. Width: 1091 pix Height: 502 pix Depth: 1 Colour channels: 4</code></pre>
<p>With <code>imager</code>, the photo is stored as a 4D numeric array. meaning the usual arithmetic operations works (for most of the time):</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="western-blot-analysis-using-rstudio.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(im)<span class="sc">+</span><span class="dv">3</span><span class="sc">*</span><span class="fu">sqrt</span>(im)</span></code></pre></div>
<pre><code>## Image. Width: 1091 pix Height: 502 pix Depth: 1 Colour channels: 4</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="western-blot-analysis-using-rstudio.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(im)</span></code></pre></div>
<pre><code>## [1] 0.881701</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="western-blot-analysis-using-rstudio.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(im)</span></code></pre></div>
<pre><code>## [1] 0.1327154</code></pre>
<p>The four dimensions are labelled x,y,z,c. We’ve already seen x and y in the plot. ‘z’ stands for the depth (and if we’re using videos also time) and ‘c’ stands for the colour. Imager will always use the x,y,z,c order.</p>
<p>A photo contains thousand of lines horzintal and vertical. Imager will scan the image beginning at the upper left corner (y=0), along the x-axis. When it’s done, it will move to the next line (y=1). It will repeat this proces until it’s done.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="western-blot-analysis-using-rstudio.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(im) <span class="co">#shows dimentions of the photo</span></span></code></pre></div>
<pre><code>## [1] 1091  502    1    4</code></pre>
<p>We can see that our Western Blot photo has 1091 lines on the x-axis and 502 lines on the y-axis. Because we’re using a photo, z always be 1. If we used a video, z will increase. At lastly our photo has 4 colour chanels. We could also get these numbers individually.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="western-blot-analysis-using-rstudio.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">width</span>(im) <span class="co">#shows the width (x-axis)</span></span></code></pre></div>
<pre><code>## [1] 1091</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="western-blot-analysis-using-rstudio.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">height</span>(im) <span class="co">#shows the height (y-axis)</span></span></code></pre></div>
<pre><code>## [1] 502</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="western-blot-analysis-using-rstudio.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">depth</span>(im) <span class="co">#shows depth (z)</span></span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="western-blot-analysis-using-rstudio.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spectrum</span>(im) <span class="co">#shows colour chanels (c)</span></span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>Imager functions mostly use photo’s with 3 color channels. Our photo has 4 color channels. which means some function won’t work and you’ll get a warning.</p>
<p>We’ll change our photo to a black and white photo, which means that our photo from now on has 1 color channel</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="western-blot-analysis-using-rstudio.html#cb27-1" aria-hidden="true" tabindex="-1"></a>im_b <span class="ot">&lt;-</span> <span class="fu">imsplit</span>(im,<span class="st">&quot;c&quot;</span>) <span class="sc">%&gt;%</span> add <span class="co">#delete color from our photo</span></span>
<span id="cb27-2"><a href="western-blot-analysis-using-rstudio.html#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">spectrum</span>(im_b) <span class="co">#show color channels on our new photo</span></span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="western-blot-analysis-using-rstudio.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)<span class="co">#load in ggplot2</span></span>
<span id="cb29-2"><a href="western-blot-analysis-using-rstudio.html#cb29-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">grayscale</span>(im_b) <span class="sc">%&gt;%</span> as.data.frame <span class="co">#convert &#39;im&#39; to gray scale, and then to a data frame</span></span></code></pre></div>
<pre><code>## Warning in grayscale(im_b): Image appears to already be in grayscale mode</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="western-blot-analysis-using-rstudio.html#cb31-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df,<span class="fu">aes</span>(x,y))<span class="sc">+</span><span class="fu">geom_raster</span>(<span class="fu">aes</span>(<span class="at">fill=</span>value)) <span class="co">#plot the photo</span></span>
<span id="cb31-2"><a href="western-blot-analysis-using-rstudio.html#cb31-2" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>We’ve a plot! But unfortunately this one isn’t very useful. If you look at code one ting might out stand the rest, we made a data frame!</p>
</div>
<div id="images-and-data-frames" class="section level3 hasAnchor" number="5.5.2">
<h3><span class="header-section-number">5.5.2</span> Images and data frames<a href="western-blot-analysis-using-rstudio.html#images-and-data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Since we have our first data frame, we might take a look at it.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="western-blot-analysis-using-rstudio.html#cb32-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">10</span>)  <span class="co">#look at the first 10 rows of the data frame</span></span></code></pre></div>
<pre><code>##     x y    value
## 1   1 1 3.858824
## 2   2 1 3.870588
## 3   3 1 3.882353
## 4   4 1 3.870588
## 5   5 1 3.870588
## 6   6 1 3.894118
## 7   7 1 3.894118
## 8   8 1 3.882353
## 9   9 1 3.882353
## 10 10 1 3.894118</code></pre>
<p>The data frame contains 3 colomns. The first 2 give us the x-y coordinates. The third colomn gives us a value. The ‘value’ is the intensity of the pixel on that place, how darker the pixel, the higher the value. There are a few problems, this dataframe has 547,682 rows, which could be a lot to plot or even work with. And a bigger problem is that we don’t exactly know which values belong to which lanes and which straps. Luckily imager has something that might help.</p>
<p>We want to locate our straps in the gel. The webite of imager shows us how locate blobs, but we’re working with straps. So we have to change some codes a bit. First we’ll get the pixels with the highest values, we treshold the image.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="western-blot-analysis-using-rstudio.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">threshold</span>(im_b,<span class="st">&quot;10%&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">plot</span>(<span class="at">main=</span><span class="st">&quot;Determinant: 90% highest values&quot;</span>) <span class="co">#In this cases we used 10%, test for your own pictures what is best</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>As you can see the straps are now darker, and the background is lighter, but some straps aren’t as visible as before. And as you can see, there is some noice added.
we’ll now label these straps.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="western-blot-analysis-using-rstudio.html#cb35-1" aria-hidden="true" tabindex="-1"></a>lab <span class="ot">&lt;-</span> <span class="fu">threshold</span>(im_b,<span class="st">&quot;10%&quot;</span>) <span class="sc">%&gt;%</span> label</span>
<span id="cb35-2"><a href="western-blot-analysis-using-rstudio.html#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lab,<span class="at">main=</span><span class="st">&quot;Labelled straps&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>There is still a lot of noise going around. We want to clear the photo a bit. To do this we use <code>isoblur</code></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="western-blot-analysis-using-rstudio.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(imager)</span>
<span id="cb36-2"><a href="western-blot-analysis-using-rstudio.html#cb36-2" aria-hidden="true" tabindex="-1"></a>nlab.denoised <span class="ot">&lt;-</span> <span class="fu">isoblur</span>(lab,<span class="dv">5</span>)</span>
<span id="cb36-3"><a href="western-blot-analysis-using-rstudio.html#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nlab.denoised)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>This is a lot better, even though our straps aren’t as clear anymore.</p>
<p>We now want to look for our straps. Imager want us to look for straps across scales, which means we’ll have to look for straps in different sizes. Unfortunately imager got updated a few times, what results in <code>get.centers</code> and <code>llply</code> not working. The reason for this is unknown. So we have to look for an other way.</p>
</div>
</div>
<div id="working-with-the-created-dataframe" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Working with the created dataframe<a href="western-blot-analysis-using-rstudio.html#working-with-the-created-dataframe" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>While I was searching for articles, I saw a photo of a SDS-page gel with graphs on the x-axis and graphs on the y-axis(unfortnely I don’t have the source anymore). I tried different ways to recreate that image, but with my own data. After some time, I might found a solution to work with this big dataframe.</p>
<p>The first step is to group the x values and the y values, we do this with the <code>group_by</code> function.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="western-blot-analysis-using-rstudio.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co">#load in dplyr package</span></span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:imager&#39;:
## 
##     where</code></pre>
<pre><code>## The following object is masked from &#39;package:EBImage&#39;:
## 
##     combine</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="western-blot-analysis-using-rstudio.html#cb43-1" aria-hidden="true" tabindex="-1"></a>data_of_x <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(x) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">mean_data =</span> <span class="fu">mean</span>(value)) <span class="co">#group by &#39;x&#39; and calculate the mean value</span></span>
<span id="cb43-2"><a href="western-blot-analysis-using-rstudio.html#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="western-blot-analysis-using-rstudio.html#cb43-3" aria-hidden="true" tabindex="-1"></a>data_of_y <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">mean_data =</span> <span class="fu">mean</span>(value)) <span class="co">#group by &#39;y&#39; and calculate the mean value</span></span></code></pre></div>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="western-blot-analysis-using-rstudio.html#cb44-1" aria-hidden="true" tabindex="-1"></a>data_of_x <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> mean_data, <span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb44-2"><a href="western-blot-analysis-using-rstudio.html#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb44-3"><a href="western-blot-analysis-using-rstudio.html#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Mean value of the pixels on the x-axis&quot;</span>, </span>
<span id="cb44-4"><a href="western-blot-analysis-using-rstudio.html#cb44-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;x-axis&quot;</span>, </span>
<span id="cb44-5"><a href="western-blot-analysis-using-rstudio.html#cb44-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Mean value of the pixels&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="western-blot-analysis-using-rstudio.html#cb45-1" aria-hidden="true" tabindex="-1"></a>data_of_y <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> mean_data, <span class="at">x =</span> y)) <span class="sc">+</span></span>
<span id="cb45-2"><a href="western-blot-analysis-using-rstudio.html#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb45-3"><a href="western-blot-analysis-using-rstudio.html#cb45-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Mean value of the pixels on the y-axis&quot;</span>, </span>
<span id="cb45-4"><a href="western-blot-analysis-using-rstudio.html#cb45-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;y-axis&quot;</span>, </span>
<span id="cb45-5"><a href="western-blot-analysis-using-rstudio.html#cb45-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Mean value of the pixels&quot;</span>) </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-11-2.png" width="672" /></p>
<p>To make the y-graph more understandble, we can flip the x- and y-axis with <code>coord_flip</code></p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="western-blot-analysis-using-rstudio.html#cb46-1" aria-hidden="true" tabindex="-1"></a>data_of_x <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> mean_data, <span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb46-2"><a href="western-blot-analysis-using-rstudio.html#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb46-3"><a href="western-blot-analysis-using-rstudio.html#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Mean value of the pixels on the x-axis&quot;</span>, </span>
<span id="cb46-4"><a href="western-blot-analysis-using-rstudio.html#cb46-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;x-axis&quot;</span>, </span>
<span id="cb46-5"><a href="western-blot-analysis-using-rstudio.html#cb46-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Mean value of the pixels&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="western-blot-analysis-using-rstudio.html#cb47-1" aria-hidden="true" tabindex="-1"></a>data_of_y <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> mean_data, <span class="at">x =</span> y)) <span class="sc">+</span></span>
<span id="cb47-2"><a href="western-blot-analysis-using-rstudio.html#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb47-3"><a href="western-blot-analysis-using-rstudio.html#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb47-4"><a href="western-blot-analysis-using-rstudio.html#cb47-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Mean value of the pixels on the y-axis&quot;</span>, </span>
<span id="cb47-5"><a href="western-blot-analysis-using-rstudio.html#cb47-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;y-axis&quot;</span>, </span>
<span id="cb47-6"><a href="western-blot-analysis-using-rstudio.html#cb47-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Mean value of the pixels&quot;</span>) </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<p>First we’ll look at the graph of the x-axis. If we imagine a rough line and make the tops more round, we can see 6 peaks. If look at the photo we used, we can see that there are 6 straps. We can now compare each strap to each other, but we have to keep in mind that there are two straps in one lane. If we just look at the graph, we can conclude for example that peak 4 (strap 4) has a higher intensity than peak 1 (strap 1), and if we compare this to the photo we used, this is true.
Using the x-axis is great when you have a different lanes with just one strap.</p>
<p>Secondly we’ll look at the graph of the y-axis. As you can see there are two peaks, a big one and a small one. Because both peaks contain multiple lanes and therefor multiple straps, we cant really make a conclusion out of the graph. What we can conclude is that there ar two rows, and that the first row has a higher intensity than the second row.</p>
</div>
<div id="the-final-product" class="section level2 hasAnchor" number="5.7">
<h2><span class="header-section-number">5.7</span> The final product<a href="western-blot-analysis-using-rstudio.html#the-final-product" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-begumWesternBlottingPowerful2022" class="csl-entry">
Begum, Habeebunnisa, Periyasamy Murugesan, and Anjana Devi Tangutur. 2022. <span>“Western Blotting: A Powerful Staple in Scientific and Biomedical Research.”</span> <em>BioTechniques</em> 73 (1): 58–69. <a href="https://doi.org/10.2144/btn-2022-0003">https://doi.org/10.2144/btn-2022-0003</a>.
</div>
<div id="ref-mahmoodWesternBlotTechnique2012" class="csl-entry">
Mahmood, Tahrin, and Ping-Chang Yang. 2012. <span>“Western Blot: Technique, Theory, and Trouble Shooting.”</span> <em>North American Journal of Medical Sciences</em> 4 (9): 429–34. <a href="https://doi.org/10.4103/1947-2714.100998">https://doi.org/10.4103/1947-2714.100998</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="the-guerrila-structure.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="relational-databases.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/005-Western_Blotting.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
